#!/bin/sh

docker-compose --version
docker-compose \
    -f docker-compose.localdev.yml \
    pull
docker-compose \
    -f docker-compose.localdev.yml \
    up --abort-on-container-exit \
    --exit-code-from=dynamodb \
    --force-recreate \
    --remove-orphans
