#!/bin/bash
set -e -u -o pipefail


git diff-index --quiet HEAD -- \
|| (echo "Working tree is dirty. Commit all changes."; false)

function deploy-function() {
    aws lambda update-function-code \
        --function-name "$1" \
        --image-uri "$2":latest
}


for FN in app; do
    deploy-function \
        $(scripts/get-staging-fn-name $FN) \
        $(scripts/get-staging-repo-url $FN)
done
